# Generated by Django 5.0.4 on 2025-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Необходимо сменить пароль при следующем входе в приложение'),
        ),
    ]
