version: '3.8'

services:
  django:
    ports:
      - "8000:8080"
    build: .
    command: gunicorn myproject.wsgi -c gunicorn.conf.py
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env

  tgbot:
    build: .
    command: python manage.py runbot
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "
        trap exit TERM;
        while :; do
          certbot renew --webroot -w /var/www/certbot --quiet &&
          nginx -s reload;
          sleep 12h;
        done"
#  Команда получения сертификата:
#  certbot certonly --webroot \
#  -w /var/www/certbot \
#  -d appsostra.ru -d storage.appsostra.ru -d admin.appsostra.ru -d web.appsostra.ru


volumes:
  static_volume:
  media_volume: