# Generated by Django 5.0.4 on 2025-02-02 21:29

import dispatch.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0015_alter_guard_managers_alter_guard_name_old'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя роли')),
            ],
            options={
                'verbose_name': 'Роль диспетчеризации',
                'verbose_name_plural': 'Роли диспетчеризации',
            },
        ),
        migrations.CreateModel(
            name='DutyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя точки дежурства')),
                ('level_1_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_1_role', to='dispatch.dutyrole', verbose_name='Дежурный уровня 1')),
                ('level_2_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_2_role', to='dispatch.dutyrole', verbose_name='Дежурный уровня 2')),
                ('level_3_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_3_role', to='dispatch.dutyrole', verbose_name='Дежурный уровня 3')),
            ],
            options={
                'verbose_name': 'Точка диспетчеризации',
                'verbose_name_plural': 'Точки диспетчеризации',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('opened', 'В работе'), ('closed', 'Выполнено')], default='opened', max_length=10)),
                ('level', models.PositiveSmallIntegerField()),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dispatch.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(storage=dispatch.models.S3MediaStorage(), upload_to='audios/')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='dispatch.incidentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=dispatch.models.S3MediaStorage(), upload_to='photos/')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='dispatch.incidentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='dispatch.incidentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=dispatch.models.S3MediaStorage(), upload_to='videos/')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='dispatch.incidentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата дежурства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.verboseuserdisplay', verbose_name='Аккаунт дежурного')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dutyrole', verbose_name='Роль дежурства')),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'Дежурства',
                'unique_together': {('date', 'role')},
            },
        ),
    ]
