# Generated by Django 5.0.4 on 2025-02-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_incident_author_alter_incident_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('opened', 'В работе'), ('closed', 'Выполнено'), ('force_closed', 'Ненадлежащее выполнение')], default='opened', max_length=12),
        ),
    ]
