# Generated by Django 5.0.4 on 2025-02-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_alter_incident_responsible_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
