# Generated by Django 5.0.4 on 2025-03-14 02:32

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_remove_notification_is_sent_notification_created_at_and_more'),
        ('myapp', '0018_alter_device_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='duty',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Окончание дежурства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duty',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало дежурства'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('start_datetime'), models.F('role'), name='unique_start_date'),
        ),
        migrations.RemoveField(
            model_name='duty',
            name='date',
        ),
    ]
