# Generated by Django 5.0.4 on 2025-08-12 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_alter_exploitationrole_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutypoint',
            options={'verbose_name': 'Система дежурств', 'verbose_name_plural': 'Система дежурств'},
        ),
        migrations.AddField(
            model_name='duty',
            name='is_forced_opened',
            field=models.BooleanField(default=False, verbose_name='Открыт ли автоматически'),
        ),
        migrations.AddField(
            model_name='duty',
            name='notification_duty_is_coming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_is_coming', to='dispatch.notification'),
        ),
        migrations.AddField(
            model_name='dutypoint',
            name='admins',
            field=models.ManyToManyField(related_name='admin_duty_points', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные лица'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Необходимо открыть дежурство ответсвенному в приложении'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='notification_need_to_open',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='need_to_open', to='dispatch.notification'),
        ),
        migrations.AlterField(
            model_name='dutypoint',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя системы дежурств'),
        ),
    ]
