# Generated by Django 5.0.4 on 2025-08-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_alter_dutypoint_options_duty_is_forced_opened_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutypoint',
            options={'verbose_name': 'Система дежурств', 'verbose_name_plural': 'Системы дежурств'},
        ),
    ]
