# Generated by Django 5.0.4 on 2025-08-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_alter_dutypoint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutypoint',
            options={'verbose_name': 'Система дежурства', 'verbose_name_plural': 'Системы дежурств'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='dispatch.dutypoint', verbose_name='Система дежурства'),
        ),
    ]
