# Generated by Django 5.0.4 on 2025-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_alter_dutypoint_options_alter_incident_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('opened', 'В работе'), ('closed', 'Выполнено'), ('force_closed', 'Ненадлежащее выполнение'), ('waiting_to_be_accepted', 'В ожидании принятия')], default='opened', max_length=50, verbose_name='Статус'),
        ),
    ]
