# Generated by Django 5.0.4 on 2025-08-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0016_remove_incident_is_accepted_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutypoint',
            name='level_0_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_0_role', to='dispatch.exploitationrole', verbose_name='Персонал, вызывающий дежурного (уровень 0)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
