# Generated by Django 5.0.4 on 2024-05-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_round_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guard',
            options={'verbose_name': 'Охранник', 'verbose_name_plural': 'Охранники'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Точка обхода', 'verbose_name_plural': 'Точки обхода'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'Обход', 'verbose_name_plural': 'Обходы'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
    ]
