# Generated by Django 5.0.4 on 2024-07-02 23:48

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_guard_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guard',
            options={'verbose_name': 'Сотрудник СБ', 'verbose_name_plural': 'Сотрудники СБ'},
        ),
        migrations.AlterField(
            model_name='guard',
            name='code',
            field=models.CharField(default=myapp.models.generate_six_digit_code, editable=False, max_length=6, unique=True, verbose_name='Код сотрудника СБ'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='manager',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'Managers'}, on_delete=django.db.models.deletion.CASCADE, related_name='guards', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='round',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guard', verbose_name='Сотрудник СБ'),
        ),
        migrations.AlterField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Обход идет'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.point', verbose_name='Точка обхода'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='myapp.round', verbose_name='Обход'),
        ),
    ]
