# Generated by Django 5.0.4 on 2024-07-03 14:17

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_guard_options_alter_guard_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guard',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='guard',
            name='code',
            field=models.CharField(default=myapp.models.generate_six_digit_code, editable=False, max_length=6, unique=True, verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='round',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guard', verbose_name='Сотрудник'),
        ),
    ]
