# Generated by Django 5.0.4 on 2024-11-30 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_guard_options_alter_guard_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='managers',
            field=models.ManyToManyField(default=None, limit_choices_to={'groups__name': 'Managers'}, related_name='guards_new', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
    ]
