# Generated by Django 5.0.4 on 2024-11-30 20:28

from django.db import migrations


def make_many_authors(apps, schema_editor):
    """
        Adds the Manager object in Guard.manager to the
        many-to-many relationship in Guard.managers
    """
    Guard = apps.get_model('myapp', 'Guard')

    for guard in Guard.objects.all():
        guard.managers.add(guard.manager)


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0007_guard_managers'),
    ]

    operations = [
        migrations.RunPython(make_many_authors),
    ]
