# Generated by Django 5.0.4 on 2024-11-30 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20241130_2355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='manager',
        ),
        migrations.AlterField(
            model_name='guard',
            name='managers',
            field=models.ManyToManyField(default=None, limit_choices_to={'groups__name': 'Managers'}, related_name='guards', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
    ]
