# Generated by Django 5.0.4 on 2024-12-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_point_expiration_date_point_point_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guard', verbose_name='Сотрудник')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.visit', verbose_name='Посещение')),
            ],
        ),
    ]
