# Generated by Django 5.0.4 on 2025-01-18 05:31

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0013_guard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerboseUserDisplay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='guard',
            old_name='name',
            new_name='name_old',
        ),
        migrations.AlterField(
            model_name='guard',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to='myapp.verboseuserdisplay', verbose_name='Аккаунт сотрудника'),
        ),
    ]
