# Generated by Django 5.0.4 on 2025-01-22 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_verboseuserdisplay_remove_guard_name_guard_name_old_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='managers',
            field=models.ManyToManyField(default=None, limit_choices_to=models.Q(('groups__name', 'Managers'), ('groups__name', 'qr_manager'), _connector='OR'), related_name='guards', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='name_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
