# Generated by Django 5.0.4 on 2025-07-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_guard_user'),
    ]

    operations = [
    ]
