# Generated by Django 5.0.4 on 2024-12-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('category', models.CharField(choices=[('first_course', 'Первое блюдо'), ('side_dish', 'Гарнир'), ('main_course', 'Второе блюдо'), ('salad', 'Салат')], max_length=50, verbose_name='Тип блюда')),
                ('photo', models.ImageField(blank=True, upload_to='dish_photos/', verbose_name='Фотография блюда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_time', models.DateField(verbose_name='Дата готовки блюда')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Pending', 'Ожидает'), ('Approved', 'Подтверждено'), ('Canceled', 'Отменено'), ('Completed', 'Завершено')], default='Pending', max_length=50, verbose_name='Статус заказа')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish', verbose_name='Блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
