# Generated by Django 5.0.4 on 2025-01-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_feedback_is_read_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина удаления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
    ]
