# Generated by Django 5.0.4 on 2025-02-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_alloweddish_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
