# Generated by Django 5.0.4 on 2025-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_photos/', verbose_name='Фотография блюда'),
        ),
    ]
