# Generated by Django 5.0.4 on 2025-03-14 02:32

import food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_feedback_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, storage=food.models.FoodS3MediaStorage(), upload_to='dish_photos/', verbose_name='Фотография блюда'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=food.models.FoodS3MediaStorage(), upload_to='feedback_photos/', verbose_name='Фотография блюда'),
        ),
    ]
