# Generated by Django 5.0.4 on 2025-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_dish_photo_alter_feedback_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('first_course', 'Первое блюдо'), ('side_dish', 'Гарнир'), ('main_course', 'Второе блюдо'), ('salad', 'Салат'), ('drink', 'Напиток')], max_length=50, verbose_name='Тип блюда'),
        ),
    ]
